---
- name: stop keycloak service
  systemd:
    name: keycloak
    daemon_reload: yes
    state: stopped
  ignore_errors: yes
  tags:
    - stop

- name: install dependency packages
  dnf:
    name:
      - wget
      - unzip
      - tar
      - vim
      - java-1.8.0-openjdk-headless
    state: present
  tags:
    - init

- name: delete keycloak directory
  file:
    path: '{{ item.path }}'
    state: absent
  with_items:
    - { path: '/opt/keycloak-{{ keycloak_version }}.tar.gz' }
    - { path: '/opt/keycloak-{{ keycloak_version }}' }
    - { path: '/opt/keycloak' }
    - { path: '/var/log/keycloak' }
    - { path: '{{ default_domain_path }}' }
  tags:
    - init

- name: download keycloak
  shell: |
    wget https://github.com/keycloak/keycloak/releases/download/{{ keycloak_version }}/keycloak-{{ keycloak_version }}.tar.gz -O /opt/keycloak-{{ keycloak_version }}.tar.gz
  args:
    warn: false
  tags:
    - init

- name: untar keycloak
  unarchive:
    src: /opt/keycloak-{{ keycloak_version }}.tar.gz
    dest: /opt/
    owner: root
    group: root
    remote_src: yes
  tags:
    - init

- name: link keycloak
  file:
    src: /opt/keycloak-{{ keycloak_version }}
    dest: /opt/keycloak
    state: link
  tags:
    - init

- name: create essential directory for keycloak
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  with_items:
    - { path: "/var/log/keycloak" }
    - { path: "/opt/keycloak/modules/system/layers/keycloak/org/postgresql/main" }
    - { path: "/opt/keycloak/domain/servers/{{ default_service_name }}/configuration" }
  tags:
    - init

- name: copy keycloak domain cluster master config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: '{{ keycloak_version }}/domain.xml.j2', dest: '/opt/keycloak/domain/configuration/domain.xml' }
  when: keycloak_list[0] == inventory_hostname
  tags:
    - domain

- name: copy keycloak domain cluster host config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: '{{ keycloak_version }}/host-master.xml.j2', dest: '/opt/keycloak/domain/configuration/host-master.xml' }
  when: keycloak_list[0] == inventory_hostname
  tags:
    - domain

- name: create domain config directory
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  with_items:
    - { path: "{{ default_domain_path }}/temp" }
    - { path: "{{ default_domain_path }}/log" }
    - { path: "{{ default_domain_path }}/data" }
    - { path: "{{ default_domain_path }}/servers/{{ default_service_name }}/configuration" }
  when: keycloak_list[0] == inventory_hostname
  tags:
    - domain
    - domain_config

- name: add master realm user
  shell: |
    /opt/keycloak/bin/add-user-keycloak.sh --domain --dc {{ default_domain_path }}/servers/{{ default_service_name }}/configuration --realm master --user {{ keycloak_mgmt_user }} --password {{ keycloak_mgmt_pass }}
  become: yes
  when: keycloak_list[0] == inventory_hostname
  tags:
    - domain
    - master_user

- name: add management user
  shell: |
    /opt/keycloak/bin/add-user.sh --user {{ keycloak_mgmt_user }} --password {{ keycloak_mgmt_pass }} --group {{ keycloak_mgmt_group }} --realm ManagementRealm --confirm-warning --display-secret
  become: yes
  register: adduser_output
  when: keycloak_list[0] == inventory_hostname
  tags:
    - slave
    - mgmt_user

- name: parse secret value
  set_fact:
    secret_value: '{{ adduser_output.stdout | join("") | regex_search(regexp, "\1") }}'
  vars:
    regexp: '.*value=\"(.*)\"'
  when: keycloak_list[0] == inventory_hostname
  tags:
    - slave
    - mgmt_user

- name: print secret_value
  debug:
    var: secret_value
  when: keycloak_list[0] == inventory_hostname
  tags:
    - slave
    - mgmt_user

- name: register adduser output
  add_host:
    name: adduser_key
    adduser_value: '{{ secret_value }}'
  when: keycloak_list[0] == inventory_hostname
  tags:
    - slave
    - mgmt_user

- name: copy keycloak domain cluster slave config files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: '{{ keycloak_version }}/host-slave.xml.j2', dest: '/opt/keycloak/domain/configuration/host-slave.xml' }
  when: keycloak_list[0] != inventory_hostname
  tags:
    - slave
    - mgmt_user

- name: download postgresql jdbc driver
  get_url:
    url: 'https://jdbc.postgresql.org/download/postgresql-{{ postgresql_jdbc_version }}.jar'
    dest: '/opt/keycloak/modules/system/layers/keycloak/org/postgresql/main'
    mode: '0644'
  tags:
    - db

- name: copy postgresql template
  template:
    src: '{{ keycloak_version }}/module-jdbc.xml.j2'
    dest: '/opt/keycloak/modules/system/layers/keycloak/org/postgresql/main/module.xml'
  tags:
    - db

- name: get public ip address 
  set_fact:
    ip4: '{{ ansible_ens18.ipv4.address }}'
  tags:
    - service
    - service_master
    - service_slave

- name: register master server ip
  add_host:
    name: master_ip
    master_value: "{{ ip4 }}"
  when: keycloak_list[0] == inventory_hostname
  tags:
    - service
    - service_master

- name: copt keycloak master service file
  template:
    src: "keycloak-master.service"
    dest: "/usr/lib/systemd/system/keycloak.service"
  vars:
    host_config: "host-master.xml"
    master_ip4: "{{ hostvars['master_ip']['master_value'] }}"
  when: keycloak_list[0] == inventory_hostname
  tags:
    - service
    - service_master

- name: start master keycloak
  systemd:
    name: keycloak
    state: started
    daemon_reload: yes
  when: keycloak_list[0] == inventory_hostname
  tags:
    - service
    - service_master

- name: Waits for port 9990
  wait_for:
    host: '{{ ip4 }}'
    port: 9990
    delay: 3
    state: started
  when: keycloak_list[0] == inventory_hostname
  tags:
    - service
    - service_master

- name: copt keycloak slave service file
  template:
    src: "keycloak-slave.service"
    dest: "/usr/lib/systemd/system/keycloak.service"
  vars:
    host_config: "host-slave.xml"
    master_ip4: "{{ hostvars['master_ip']['master_value'] }}"
  when: keycloak_list[0] != inventory_hostname
  tags:
    - service
    - service_slave

- name: start slave keycloak
  systemd:
    name: keycloak
    state: started
    daemon_reload: yes
  when: keycloak_list[0] != inventory_hostname
  tags:
    - service
    - service_slave
