---
- name: os setting
  hosts: '{{ hosts | default("all") }}'
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo

  vars:
    keycloak_mgmt_user: '{{ lookup("env","KEYCLOAK_MGMT_USER") }}'
    keycloak_mgmt_pass: '{{ lookup("env","KEYCLOAK_MGMT_PASS") }}'
    keycloak_mgmt_group: '{{ lookup("env","KEYCLOAK_MGMT_GROUP") }}'

  roles:
    - osenv
