---
- name: wait for connection to be installed os
  wait_for_connection:
    sleep: 1
    connect_timeout: 1
    timeout: 1800
  tags:
    - wait

- name: sleep for cluster to be ready
  wait_for:
    port: 22
    state: started
    timeout: 600
  tags:
    - wait

- name: set dns order
  shell: |
    nmcli conn modify "System ens18" ipv4.dns-priority 50
    nmcli conn up "System ens18"
  tags:
    - dns

- name: set hostname
  shell: |
    hostnamectl set-hostname '{{ inventory_hostname }}'
  tags:
    - hostname

- name: set selinux mode to permissive
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'
  tags:
    - selinux

- name: disable firewalld
  systemd:
    name: firewalld
    enabled: no
  tags:
    - firewalld

- name: stop firewalld
  systemd: 
    name: firewalld
    state: stopped
  tags:
    - firewalld

- name: clean yum cache
  command: yum clean all
  args:
    warn: false
  tags:
    - yum

- name: update repo cache
  yum:
    update_cache: yes
  tags:
    - yum

- name: install jdk
  yum:
    name:
      - wget
      - unzip
      - tar
      - vim
      - java-1.8.0-openjdk-headless
    state: present
  tags:
    - command

- name: reboot cluster
  reboot:
    reboot_timeout: 180
  tags:
    - reboot
